# Generated by Django 6.0 on 2025-12-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('high_score', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('choices', models.JSONField(help_text="A list of 3-4 string choices, e.g., ['A', 'B', 'C', 'D']")),
                ('correct_answer', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('GTV', 'Guess the Verse'), ('WST', 'Who Said This?'), ('ONT', 'Old or New Testament')], default='GTV', max_length=3)),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField(default=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('streak_placeholder', models.IntegerField(default=0)),
            ],
        ),
    ]
