# Generated by Django 6.0 on 2025-12-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='leaderboardentry',
            options={'verbose_name_plural': 'Leaderboard Entries'},
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='streak_placeholder',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='current_streak',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='group_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
