# Generated by Django 6.0 on 2025-12-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReminderSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="User's email address for reminders.", max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to stop sending emails to this user.')),
            ],
        ),
    ]
