# Generated by Django 6.0 on 2025-12-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0004_studygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyremindersubscriber',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
    ]
